### ISSUE TITLE
textView frame strange behaviour

### ISSUE THREAD

**Issue by timqzm** [contentful-labs/rich-text-renderer.swift#6] opened 2019-08-08 06:35 UTC
I've tried to put my RichTextViewController subclass in a navigation controller (programmatically), and I've got 64pt gap at the bottom.
<img width="432" alt="Screenshot 2019-08-07 at 17 14 12" src="https://user-images.githubusercontent.com/13407092/62679908-99fe1080-b9be-11e9-8e0a-bb84d2fabb60.png">
I've played with different approaches to set it on my screen with very strange results:
<img width="422" alt="Screenshot 2019-08-07 at 20 45 24" src="https://user-images.githubusercontent.com/13407092/62679941-b13cfe00-b9be-11e9-9dbe-40de3d8e3358.png">
<img width="422" alt="Screenshot 2019-08-07 at 20 43 53" src="https://user-images.githubusercontent.com/13407092/62680289-915a0a00-b9bf-11e9-951c-8637adb9b4e9.png">
<img width="422" alt="Screenshot 2019-08-07 at 20 44 59" src="https://user-images.githubusercontent.com/13407092/62680310-9f0f8f80-b9bf-11e9-8483-2cb75995d536.png">
The only way I found when it looks good is to init RichTextViewController subclass from coder, placed it in container view in navigation root controller 🙃
<img width="711" alt="Screenshot 2019-08-08 at 08 29 51" src="https://user-images.githubusercontent.com/13407092/62680321-a6cf3400-b9bf-11e9-9192-bd7f8af7fc5a.png">

**Comment by mysimonbrodowski** [comment] 2019-10-31 18:22
Hi @timqzm 
Can you help me?
Is it possible to get the content size of RichTextViewController when the RichTextDocument is loaded fully?
I need to calculate it correctly.

**Comment by timqzm** [comment] 2019-10-31 19:05
I finished up with `textViewController?.textView.contentSize.height` in `viewDidAppear` and it was impractical to spend more time on this question.
If you find an earlier way please let me know 😊

**Comment by tomkowz** [comment] 2020-09-02 17:36
@timqzm in the `0.2.0` it seems like the issue is fixed. Please find a screenshot with example attached.

<img width="559" alt="navigation-controller" src="https://user-images.githubusercontent.com/2303177/92016810-29592d00-ed53-11ea-912f-091e0ac8d255.png">

I'll close it for now. Please open a new issue when the problem still occurs.

**Closed** 2020-09-02 17:36 UTC
